name: triton-linalg_ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      matrix:
        triton-linalg_version : [v1.1.1]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: run_triton-linalg_ci
        run: >
          bash .github/ci_script/triton-linalg-ci_script.sh
